/var/spool/slurm/slurmd/state/job1070964/slurm_script: line 8: workon: command not found
Looking for config file in /cluster/project/hilliges/mbressieux/log/chickchicken/cfg_args
Config file found: /cluster/project/hilliges/mbressieux/log/chickchicken/cfg_args
Rendering /cluster/project/hilliges/mbressieux/log/chickchicken
Loading trained model at iteration 20000 [03/07 18:19:26]
Found dataset.json file, assuming Nerfies data set! [03/07 18:19:26]
Reading Nerfies Info [03/07 18:19:26]
 [03/07 18:19:30]
Loading Training Cameras [03/07 18:19:30]
Loading Test Cameras [03/07 18:19:31]
Rendering progress - segmenting:   0%|          | 0/114 [00:00<?, ?it/s]Rendering progress - segmenting:   0%|          | 0/114 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/home/mbressieux/network_DSU/Deformable-3D-Gaussians/render.py", line 581, in <module>
    render_sets(
  File "/cluster/home/mbressieux/network_DSU/Deformable-3D-Gaussians/render.py", line 533, in render_sets
    render_func(
  File "/cluster/home/mbressieux/network_DSU/Deformable-3D-Gaussians/render.py", line 134, in segment_dynamic_gaussian
    results = render(
              ^^^^^^^
  File "/cluster/home/mbressieux/network_DSU/Deformable-3D-Gaussians/gaussian_renderer/__init__.py", line 173, in render
    save_npy(means3D, "means3D_" + name_iter + ".npy", root=root)
                      ~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /cluster/home/mbressieux/.cache/torch/hub/checkpoints/vgg16-397923af.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 1451, in connect
    super().connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/mbressieux/network_DSU/Deformable-3D-Gaussians/metrics.py", line 104, in <module>
    lpips_fn = lpips.LPIPS(net='vgg').to(device)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/lpips/lpips.py", line 84, in __init__
    self.net = net_type(pretrained=not self.pnet_rand, requires_grad=self.pnet_tune)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/lpips/pretrained_networks.py", line 99, in __init__
    vgg_pretrained_features = tv.vgg16(pretrained=pretrained).features
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/vgg.py", line 433, in vgg16
    return _vgg("D", False, weights, progress, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/vgg.py", line 105, in _vgg
    model.load_state_dict(weights.get_state_dict(progress=progress, check_hash=True))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torchvision/models/_api.py", line 90, in get_state_dict
    return load_state_dict_from_url(self.url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torch/hub.py", line 760, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/cluster/project/hilliges/mbressieux/.virtualenvs/Def3DGS/lib/python3.11/site-packages/torch/hub.py", line 622, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
